# setting up frontend update public ip in the r53 record
- name: setting up frontend
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present
# lets do the enabling after configuration
#  - name: start and enable nginx service
#    ansible.builtin.service:
#      name: nginx service
#      enabled: yes
#      state: restarted

  - name: remove directory to delete default
    ansible.builtin.file:
      path:  /usr/share/nginx/html
      state: absent

  - name: create dir
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download frontend content
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: Extract archive
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy configuration for roboshop
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: start and enable nginx service
    ansible.builtin.service:
      name: nginx service
      enabled: yes
      state: restarted